name: Izrada Windows EXE datoteke

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Preuzmi kod iz repozitorija
      uses: actions/checkout@v4

    - name: Postavi Python okruženje
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Instaliraj PyInstaller
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller

    - name: Zapakiraj Python program u EXE
      run: |
        pyinstaller --onefile main.py

    - name: Spremi gotov EXE kao rezultat
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Program-EXE
        path: dist/*.exe
